### ISSUE TITLE
Create a Hello World tutorial

### ISSUE THREAD

**Issue by jaimalchohan** [jaimalchohan/mini-web-deploy#5]
Create a Hello World tutorial that walks users through their first use of MiniWebDeploy

**Comment by Piedone** [comment]
Just wanted to say, very interesting project! Have you used it with Azure Cloud Services?

**Comment by jaimalchohan** [comment]
Hi @Piedone I haven't yet, but definitely something I will be looking at in the next few weeks once I have most of the large requirements complete.

**Comment by jaimalchohan** [comment]
https://github.com/jaimalchohan/mini-web-deploy/wiki/Hello-World

**Comment by Piedone** [comment]
@jaimalchohan OK, thanks!
